name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x86
      
      - name: Build Windows DLL
        run: |
          cl.exe /nologo /std:c11 /O2 /LD /DNDEBUG prof.c ws2_32.lib /Fe:prof.dll
      
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-dll
          path: prof.dll

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib
      
      - name: Build Linux SO
        run: |
          gcc -std=c11 -m32 -shared -fPIC -Ofast -s -DNDEBUG prof.c -pthread -o libprof.so
      
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-so
          path: libprof.so

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get Short Git Hash
        id: git_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Latest Supported BYOND Version
        id: byond_version
        run: |
          # Extract the 3rd field from "#define BYOND_MAX_BUILD 1337" using space as delimiter
          max_build=$(grep "BYOND_MAX_BUILD" offsets/windows.h | cut -d' ' -f3)
          echo "version=$max_build" >> $GITHUB_OUTPUT
        
      - uses: actions/download-artifact@v4
      
      - name: Display structure of downloaded files
        run: ls -R
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: build-${{ steps.git_hash.outputs.hash }}
          name: ${{ steps.byond_version.outputs.version }} (build ${{ steps.git_hash.outputs.hash }})
          files: |
            windows-dll/prof.dll
            linux-so/libprof.so
